### ISSUE TITLE
If node started with --inspect, error trying to start inspector

### ISSUE THREAD

**Issue by tcollinsworth** [tcollinsworth/profiler-heapdump#1]
Attempt to detect inspector is running and try to use existing inspect and don't close it.

```
ERROR [1654566852064] (******************************):
    message: "Inspector is already activated. Close it with inspector.close() before activating it again."
    err: {
      "type": "NodeError",
      "message": "Inspector is already activated. Close it with inspector.close() before activating it again.",
      "stack":
          Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
              at new NodeError (internal/errors.js:322:7)
              at Proxy.inspectorOpen (inspector.js:137:11)
```

**Comment by tcollinsworth** [comment]
Resolved.
